<a href="https://colab.research.google.com/github/pqvinicius/logica-programacao-em-python-uninter/blob/main/_LOGICA_DE_PROGRAMA%C3%87%C3%83O_EM_PYTHON_UNINTER_AP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# LOGICA DE PROGRAMAÇÃO EM PYTHON
# AULAS DE PYTHON DA UNINTER
# COLOCAREI AS AULAS PRATICAS AQUI


# **AULA 1** - TRABALHANDO COM NUMPY E POTLY

In [3]:
#importações de libs
import numpy as np
import plotly.express as px

In [4]:
#diferença entre array numpy para list in python

#lista normal
num_elementos = 10000000
lista_elementos =[]
for x in range(num_elementos):
  lista_elementos.append(x)
print(lista_elementos[-1])

9999999


In [5]:
# lista numpy
array_elementos = np.arange(num_elementos)
print(array_elementos[-1])

9999999


##**Criação de Arrays em Numpy**

In [6]:

array_teste = np.array([1,2,3,4,5,7,8,9,10])
print(f'COM VARIAVEL: Criação de array numpy utilizando o método .array:\n{array_teste}\n')
print(f'DIRETO NO PRINT: Criação de array numpy utilizando o método .array:\n{np.array([1,2,3,4,5,7,8,9,10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de zeros utilizando o método .zeros:\n{np.zeros([10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .ones:\n{np.ones([10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .empy:\n{np.empty([10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .arange:\n{np.arange(10)}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .linspace:\n{np.linspace(0,100,num=101)}\n')



COM VARIAVEL: Criação de array numpy utilizando o método .array:
[ 1  2  3  4  5  7  8  9 10]

DIRETO NO PRINT: Criação de array numpy utilizando o método .array:
[ 1  2  3  4  5  7  8  9 10]

DIRETO NO PRINT: Criação de array numpy de zeros utilizando o método .zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .empy:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .arange:
[0 1 2 3 4 5 6 7 8 9]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .linspace:
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  

##**Tipos de Dados**

In [7]:
array_perfomance = np.zeros(num_elementos)
print(array_perfomance.dtype) #verificando tipo de dado do aray
print(array_perfomance)
array_perfomance = np.zeros(num_elementos, dtype=np.int8)
print(array_perfomance.dtype)
print(array_perfomance)

float64
[0. 0. 0. ... 0. 0. 0.]
int8
[0 0 0 ... 0 0 0]


##**Criação de Números Randômicos e Vetor/Matriz/Tensor**



In [8]:
x = np.random.default_rng()
print(x.random(10))

[0.09141203 0.7457615  0.36740243 0.47718301 0.5658366  0.66510976
 0.41340328 0.2789268  0.9484787  0.04136698]


In [9]:
rng = np.random.default_rng(12345)
vetor = rng.random(4)
print(f'Array de 1 Dimensão (VETOR) randômico: \n{vetor}\n')
matriz = rng.random([4,4])
print(f'Array de 2 Dimensões (MATRIZ) randômico: \n{matriz}\n')
tensor = rng.random([4,4,4])
print(f'Array de 3 Dimensões (TENSOR) randômico: \n{tensor}\n')

Array de 1 Dimensão (VETOR) randômico: 
[0.22733602 0.31675834 0.79736546 0.67625467]

Array de 2 Dimensões (MATRIZ) randômico: 
[[0.39110955 0.33281393 0.59830875 0.18673419]
 [0.67275604 0.94180287 0.24824571 0.94888115]
 [0.66723745 0.09589794 0.44183967 0.88647992]
 [0.6974535  0.32647286 0.73392816 0.22013496]]

Array de 3 Dimensões (TENSOR) randômico: 
[[[0.08159457 0.1598956  0.34010018 0.46519315]
  [0.26642103 0.8157764  0.19329439 0.12946908]
  [0.09166475 0.59856801 0.8547419  0.60162124]
  [0.93198836 0.72478136 0.86055132 0.9293378 ]]

 [[0.54618601 0.93767296 0.49498794 0.27377318]
  [0.45177871 0.66503892 0.33089093 0.90345401]
  [0.25707418 0.33982834 0.2588534  0.35544648]
  [0.00502233 0.62860454 0.28238271 0.06808769]]

 [[0.61682898 0.17632632 0.30438839 0.44088681]
  [0.15020234 0.21792886 0.47433312 0.47636886]
  [0.25523235 0.29756527 0.27906712 0.26057921]
  [0.48276159 0.21197904 0.4956306  0.24626133]]

 [[0.83848265 0.18013059 0.86215629 0.17829944]
  [0.7505

##**Ordenação e ADD elementos**

In [10]:
rng = np.random.default_rng()
array_1 = rng.random([2,5])
print(f'Array 1 SEM ORDENAÇÃO:\n{array_1}\n')
print(f'Array 1 COM ORDENAÇÃO:\n{np.sort(array_1)}\n')
print(f'Array 1 COM ORDENAÇÃO:\n{np.sort(array_1,  axis = 0)}\n')
print(f'Array 1 COM ORDENAÇÃO:\n{np.sort(array_1, axis = 1)}\n')

# CONCATENAÇÃO

array_2 = rng.random([2,1])
print(f'ARRAY 2:\n{array_2}\n')

array_concatenado = np.concatenate([array_1,array_2], axis = 1)
print(f'Array Concatenado:\n{array_concatenado}\n')

array_concatenado_2 = np.hstack([array_1,array_2])
print(f'Array Concatenado:\n{array_concatenado_2}\n')


Array 1 SEM ORDENAÇÃO:
[[0.7941118  0.78031812 0.76523861 0.83279792 0.60247246]
 [0.80117089 0.49030166 0.21359536 0.2062198  0.94620249]]

Array 1 COM ORDENAÇÃO:
[[0.60247246 0.76523861 0.78031812 0.7941118  0.83279792]
 [0.2062198  0.21359536 0.49030166 0.80117089 0.94620249]]

Array 1 COM ORDENAÇÃO:
[[0.7941118  0.49030166 0.21359536 0.2062198  0.60247246]
 [0.80117089 0.78031812 0.76523861 0.83279792 0.94620249]]

Array 1 COM ORDENAÇÃO:
[[0.60247246 0.76523861 0.78031812 0.7941118  0.83279792]
 [0.2062198  0.21359536 0.49030166 0.80117089 0.94620249]]

ARRAY 2:
[[0.83650212]
 [0.66050703]]

Array Concatenado:
[[0.7941118  0.78031812 0.76523861 0.83279792 0.60247246 0.83650212]
 [0.80117089 0.49030166 0.21359536 0.2062198  0.94620249 0.66050703]]

Array Concatenado:
[[0.7941118  0.78031812 0.76523861 0.83279792 0.60247246 0.83650212]
 [0.80117089 0.49030166 0.21359536 0.2062198  0.94620249 0.66050703]]



##**Conhecendo o seu array**

In [11]:
rng = np.random.default_rng()
array_teste_4=rng.random([23,43,17])
# print(array_teste_4) #tensor gigante, muito dificil de saber dados

# descobrindo dados do array

print(f'Quais são as suas dimensões?\n{array_teste_4.ndim}\n')
print(f'Quais o seu formato?\n{array_teste_4.shape}\n')
print(f'Qauntos elementos possui?\n{array_teste_4.size}\n')

Quais são as suas dimensões?
3

Quais o seu formato?
(23, 43, 17)

Qauntos elementos possui?
16813



##**Como mudar o formato de um array**

In [12]:
x = np.arange(0,20)
print(f'Array x:\n{x}\n')
x = x.reshape(4,5)
print(f'Array x:\n{x}\n')
x = x.flatten()
print(f'Array x:\n{x}\n')
y=x.reshape([4,5])
print(f'Array y:\n{y}\n')
y=np.vsplit(y,4)
print(f'Array y:\n{y}\n')


Array x:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array x:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array x:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array y:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array y:
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]



## PLOTLY

In [13]:
#Criando arrays para montar

a = 3/4
b = 2/4
c = 1/4
vetor_a=np.ones(20)
vetor_b=np.ones(20)
vetor_c=np.ones(20)

for i in range (20):
  vetor_a[i]= vetor_a[i - 1] = a**i
  vetor_b[i]= vetor_b[i - 1] = b**i
  vetor_c[i]= vetor_c[i - 1] = c**i
# print(vetor_a)
# print(vetor_b)
# print(vetor_c)

np.savetxt('vetor_a.txt', vetor_a, fmt ='%f', delimiter=';')
np.savetxt('vetor_b.txt', vetor_b, fmt ='%f', delimiter=';')
np.savetxt('vetor_c.txt', vetor_c, fmt ='%f', delimiter=';')


##Plotly - Criando nosso primeiro grafico

In [14]:
array_a = np.loadtxt('vetor_a.txt', dtype = np.float64, delimiter = ';')
array_b = np.loadtxt('vetor_b.txt', dtype = np.float64, delimiter = ';')
array_c = np.loadtxt('vetor_c.txt', dtype = np.float64, delimiter = ';')

# print(array_a)
# print(array_b)
# print(array_c)

array_abc = np.vstack([array_a, array_b, array_c])
print(array_abc)
array_abc = array_abc.transpose()
fig = px.scatter(array_abc,
                 title = 'Gráfico de dispersão teste')
fig.show()
fig2 = px.line(array_abc,
               title = 'Gráfico de linha teste')
fig2.show()

[[7.50000e-01 5.62500e-01 4.21875e-01 3.16406e-01 2.37305e-01 1.77979e-01
  1.33484e-01 1.00113e-01 7.50850e-02 5.63140e-02 4.22350e-02 3.16760e-02
  2.37570e-02 1.78180e-02 1.33630e-02 1.00230e-02 7.51700e-03 5.63800e-03
  4.22800e-03 4.22800e-03]
 [5.00000e-01 2.50000e-01 1.25000e-01 6.25000e-02 3.12500e-02 1.56250e-02
  7.81200e-03 3.90600e-03 1.95300e-03 9.77000e-04 4.88000e-04 2.44000e-04
  1.22000e-04 6.10000e-05 3.10000e-05 1.50000e-05 8.00000e-06 4.00000e-06
  2.00000e-06 2.00000e-06]
 [2.50000e-01 6.25000e-02 1.56250e-02 3.90600e-03 9.77000e-04 2.44000e-04
  6.10000e-05 1.50000e-05 4.00000e-06 1.00000e-06 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00]]


# AULA 2 - TRABALHANDO COM PANDAS

In [15]:
import pandas as pd

#importando o arquivo
df = pd.read_csv('/content/glp-2025-01.csv', on_bad_lines='skip', sep=None,engine= 'python')


## Manipulação de dados

In [16]:
df.head() #entendo os dados

Regiao - Sigla Estado - Sigla            Municipio  \
0              SE             SP              JACAREI   
1              SE             SP              JACAREI   
2              SE             SP              JACAREI   
3              SE             SP  SAO JOSE DOS CAMPOS   
4              NE             PB          JOAO PESSOA   

                        Revenda      CNPJ da Revenda  \
0   AUTO CENTER SANTA CRUZ LTDA   02.831.138/0001-68   
1    PETROTRUCK AUTO POSTO LTDA   06.276.865/0001-61   
2         AUTO POSTO R N M LTDA   59.790.436/0001-74   
3  AUTO CENTER PAIVA & CIA LTDA   63.957.708/0001-55   
4          MURILO JOSE FERREIRA   01.998.829/0001-98   

                      Nome da Rua Numero Rua Complemento  \
0  AVENIDA SANTA CRUZ DOS LAZAROS        805         NaN   
1   RUA ANTONIO DE OLIVEIRA FILHO         36         NaN   
2             RODOVIA NILO MAXIMO       3550        KM 4   
3         AVENIDA BENEDITO FRIGGI       3400         NaN   
4    RUA JORNALISTA RAFAEL MORORO        S?N         NaN   

                       Bairro        Cep Produto Data da Coleta  \
0        STA CRUZ DOS LAZAROS  12322-310     GLP     01/01/2025   
1         CIDADE NOVA JACAREI  12325-160     GLP     01/01/2025   
2  SANTO ANTONIO DA BOA VISTA  12315-010     GLP     01/01/2025   
3         JARDIM NOVA DETROIT  12224-480     GLP     01/01/2025   
4                      RANGEL  58070-130     GLP     01/01/2025   

  Valor de Venda  Valor de Compra Unidade de Medida              Bandeira  
0           98,9              NaN        R$ / 13 kg                BRANCA  
1          89,99              NaN        R$ / 13 kg                BRANCA  
2             99              NaN        R$ / 13 kg  SUPERGASBRAS ENERGIA  
3           98,9              NaN        R$ / 13 kg   NACIONAL GÁS BUTANO  
4            110              NaN        R$ / 13 kg   NACIONAL GÁS BUTANO

In [17]:
#informações das colunas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71780 entries, 0 to 71779
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Regiao - Sigla    71780 non-null  object 
 1   Estado - Sigla     71780 non-null  object 
 2   Municipio          71780 non-null  object 
 3   Revenda            71780 non-null  object 
 4   CNPJ da Revenda    71780 non-null  object 
 5   Nome da Rua        71780 non-null  object 
 6   Numero Rua         71780 non-null  object 
 7   Complemento        18684 non-null  object 
 8   Bairro             71780 non-null  object 
 9   Cep                71780 non-null  object 
 10  Produto            71780 non-null  object 
 11  Data da Coleta     71780 non-null  object 
 12  Valor de Venda     71780 non-null  object 
 13  Valor de Compra    0 non-null      float64
 14  Unidade de Medida  71780 non-null  object 
 15  Bandeira           71780 non-null  object 
dtypes: float64(1), object(

In [18]:
#trazendo colunas importantes
dfColunas = ['Estado - Sigla', 'Municipio', 'Revenda','Produto', 'Data da Coleta', 'Valor de Venda', 'Bandeira']
dfAtual = df.filter(items=dfColunas)
dfAtual

Estado - Sigla             Municipio                       Revenda  \
0                 SP               JACAREI   AUTO CENTER SANTA CRUZ LTDA   
1                 SP               JACAREI    PETROTRUCK AUTO POSTO LTDA   
2                 SP               JACAREI         AUTO POSTO R N M LTDA   
3                 SP   SAO JOSE DOS CAMPOS  AUTO CENTER PAIVA & CIA LTDA   
4                 PB           JOAO PESSOA          MURILO JOSE FERREIRA   
...              ...                   ...                           ...   
71775             AM                MANAUS          SOCIEDADE FOGAS LTDA   
71776             AM                MANAUS          SOCIEDADE FOGAS LTDA   
71777             AM                MANAUS          SOCIEDADE FOGAS LTDA   
71778             BA  VITORIA DA CONQUISTA                 PETROGAS LTDA   
71779             AM                MANAUS          SOCIEDADE FOGAS LTDA   

      Produto Data da Coleta Valor de Venda              Bandeira  
0         GLP     01/01/2025           98,9                BRANCA  
1         GLP     01/01/2025          89,99                BRANCA  
2         GLP     01/01/2025             99  SUPERGASBRAS ENERGIA  
3         GLP     01/01/2025           98,9   NACIONAL GÁS BUTANO  
4         GLP     01/01/2025            110   NACIONAL GÁS BUTANO  
...       ...            ...            ...                   ...  
71775     GLP     30/06/2025            121                 FOGAS  
71776     GLP     30/06/2025            120                 FOGAS  
71777     GLP     30/06/2025            121                 FOGAS  
71778     GLP     30/06/2025            115  SUPERGASBRAS ENERGIA  
71779     GLP     30/06/2025            120                 FOGAS  

[71780 rows x 7 columns]

In [19]:
#alterar nome da coluna
dfAtual = dfAtual.rename(columns={'Estado - Sigla':'UF'})

In [20]:
dfAtual

UF             Municipio                       Revenda Produto  \
0      SP               JACAREI   AUTO CENTER SANTA CRUZ LTDA     GLP   
1      SP               JACAREI    PETROTRUCK AUTO POSTO LTDA     GLP   
2      SP               JACAREI         AUTO POSTO R N M LTDA     GLP   
3      SP   SAO JOSE DOS CAMPOS  AUTO CENTER PAIVA & CIA LTDA     GLP   
4      PB           JOAO PESSOA          MURILO JOSE FERREIRA     GLP   
...    ..                   ...                           ...     ...   
71775  AM                MANAUS          SOCIEDADE FOGAS LTDA     GLP   
71776  AM                MANAUS          SOCIEDADE FOGAS LTDA     GLP   
71777  AM                MANAUS          SOCIEDADE FOGAS LTDA     GLP   
71778  BA  VITORIA DA CONQUISTA                 PETROGAS LTDA     GLP   
71779  AM                MANAUS          SOCIEDADE FOGAS LTDA     GLP   

      Data da Coleta Valor de Venda              Bandeira  
0         01/01/2025           98,9                BRANCA  
1         01/01/2025          89,99                BRANCA  
2         01/01/2025             99  SUPERGASBRAS ENERGIA  
3         01/01/2025           98,9   NACIONAL GÁS BUTANO  
4         01/01/2025            110   NACIONAL GÁS BUTANO  
...              ...            ...                   ...  
71775     30/06/2025            121                 FOGAS  
71776     30/06/2025            120                 FOGAS  
71777     30/06/2025            121                 FOGAS  
71778     30/06/2025            115  SUPERGASBRAS ENERGIA  
71779     30/06/2025            120                 FOGAS  

[71780 rows x 7 columns]

In [21]:
#Quantidade de entradas por UF
colunaUF = dfAtual['UF']
colunaUF = colunaUF.value_counts()
pUF = [100*sigla/colunaUF.sum() for sigla in colunaUF]
pUF

[np.float64(21.968514906659237),
 np.float64(10.28002229033157),
 np.float64(7.587071607690165),
 np.float64(7.135692393424352),
 np.float64(6.616049038729451),
 np.float64(4.547227640011145),
 np.float64(4.33268319866258),
 np.float64(3.6667595430482027),
 np.float64(3.293396489272778),
 np.float64(2.943716912789078),
 np.float64(2.9256060183895234),
 np.float64(2.6344385622736137),
 np.float64(2.5898578991362498),
 np.float64(2.5842853162440793),
 np.float64(2.116188353301755),
 np.float64(1.9852326553357482),
 np.float64(1.6968514906659236),
 np.float64(1.5171356923934243),
 np.float64(1.412649763165227),
 np.float64(1.3360267483978825),
 np.float64(1.2552242964614098),
 np.float64(1.179994427417108),
 np.float64(1.1744218445249373),
 np.float64(0.9612705488994149),
 np.float64(0.9292281972694344),
 np.float64(0.8080245193647255),
 np.float64(0.5224296461409863)]

In [22]:
#Media de preço GLP por estado

dfAtual['Valor de Venda'] = dfAtual['Valor de Venda'].str.replace(',','.')
dfAtual['Valor de Venda'] = dfAtual['Valor de Venda'].astype(float)
dfColunas =['UF','Valor de Venda']
dffiltrado = dfAtual.filter(items=dfColunas)
dffiltrado = dffiltrado.groupby('UF').mean().sort_values(by='Valor de Venda', ascending=False)
dffiltrado

Valor de Venda
UF                
RR      137.136207
AM      127.099941
TO      125.862999
RO      122.670306
AC      122.237681
AP      119.696000
BA      119.388759
SC      119.236933
MT      118.968514
MA      115.355680
MS      112.027189
RS      111.463032
PA      110.815131
GO      108.262341
CE      107.841649
SP      107.136496
PI      105.700678
MG      105.120861
RN      104.927628
PB      104.717931
SE      103.989460
PR      103.757442
DF      101.802242
AL      100.293590
ES       99.624605
RJ       98.577484
PE       97.817105

In [23]:
dffiltrado = dffiltrado.reset_index()
fig = px.bar(
    dffiltrado,
    x='Valor de Venda',
    y='UF',
    orientation='h',
    title = 'Preço médio do GLP por UF',
     labels={
        'Valor de Venda': 'Preço Médio (R$)',
        'index': 'UF'
    }
)

fig.show()

## Pandas Profilling (YDATA)

In [24]:

from ydata_profiling import ProfileReport

In [25]:
profile = ProfileReport(dfAtual)
profile.to_notebook_iframe()
profile.tofile('saida.html')


Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|██████████| 7/7 [00:01<00:00,  5.47it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

AttributeError: 'ProfileReport' object has no attribute 'tofile'