<a href="https://colab.research.google.com/github/pqvinicius/logica-programacao-em-python-uninter/blob/main/_LOGICA_DE_PROGRAMA%C3%87%C3%83O_EM_PYTHON_UNINTER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
# LOGICA DE PROGRAMAÇÃO EM PYTHON
# AULAS DE PYTHON DA UNINTER
# COLOCAREI AS AULAS PRATICAS AQUI


# **AULA 1** - TRABALHANDO COM NUMPY E POTLY

In [48]:
#importações de libs
import numpy as np
import plotly.express as px

In [49]:
#diferença entre array numpy para list in python

#lista normal
num_elementos = 10000000
lista_elementos =[]
for x in range(num_elementos):
  lista_elementos.append(x)
print(lista_elementos[-1])

9999999


In [50]:
# lista numpy
array_elementos = np.arange(num_elementos)
print(array_elementos[-1])

9999999


##**Criação de Arrays em Numpy**

In [51]:

array_teste = np.array([1,2,3,4,5,7,8,9,10])
print(f'COM VARIAVEL: Criação de array numpy utilizando o método .array:\n{array_teste}\n')
print(f'DIRETO NO PRINT: Criação de array numpy utilizando o método .array:\n{np.array([1,2,3,4,5,7,8,9,10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de zeros utilizando o método .zeros:\n{np.zeros([10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .ones:\n{np.ones([10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .empy:\n{np.empty([10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .arange:\n{np.arange(10)}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .linspace:\n{np.linspace(0,100,num=101)}\n')



COM VARIAVEL: Criação de array numpy utilizando o método .array:
[ 1  2  3  4  5  7  8  9 10]

DIRETO NO PRINT: Criação de array numpy utilizando o método .array:
[ 1  2  3  4  5  7  8  9 10]

DIRETO NO PRINT: Criação de array numpy de zeros utilizando o método .zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .empy:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .arange:
[0 1 2 3 4 5 6 7 8 9]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .linspace:
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  

##**Tipos de Dados**

In [52]:
array_perfomance = np.zeros(num_elementos)
print(array_perfomance.dtype) #verificando tipo de dado do aray
print(array_perfomance)
array_perfomance = np.zeros(num_elementos, dtype=np.int8)
print(array_perfomance.dtype)
print(array_perfomance)

float64
[0. 0. 0. ... 0. 0. 0.]
int8
[0 0 0 ... 0 0 0]


##**Criação de Números Randômicos e Vetor/Matriz/Tensor**



In [53]:
x = np.random.default_rng()
print(x.random(10))

[0.10710994 0.77513899 0.55797776 0.38500789 0.5488579  0.37167344
 0.82201556 0.18750499 0.80107986 0.26898028]


In [54]:
rng = np.random.default_rng(12345)
vetor = rng.random(4)
print(f'Array de 1 Dimensão (VETOR) randômico: \n{vetor}\n')
matriz = rng.random([4,4])
print(f'Array de 2 Dimensões (MATRIZ) randômico: \n{matriz}\n')
tensor = rng.random([4,4,4])
print(f'Array de 3 Dimensões (TENSOR) randômico: \n{tensor}\n')

Array de 1 Dimensão (VETOR) randômico: 
[0.22733602 0.31675834 0.79736546 0.67625467]

Array de 2 Dimensões (MATRIZ) randômico: 
[[0.39110955 0.33281393 0.59830875 0.18673419]
 [0.67275604 0.94180287 0.24824571 0.94888115]
 [0.66723745 0.09589794 0.44183967 0.88647992]
 [0.6974535  0.32647286 0.73392816 0.22013496]]

Array de 3 Dimensões (TENSOR) randômico: 
[[[0.08159457 0.1598956  0.34010018 0.46519315]
  [0.26642103 0.8157764  0.19329439 0.12946908]
  [0.09166475 0.59856801 0.8547419  0.60162124]
  [0.93198836 0.72478136 0.86055132 0.9293378 ]]

 [[0.54618601 0.93767296 0.49498794 0.27377318]
  [0.45177871 0.66503892 0.33089093 0.90345401]
  [0.25707418 0.33982834 0.2588534  0.35544648]
  [0.00502233 0.62860454 0.28238271 0.06808769]]

 [[0.61682898 0.17632632 0.30438839 0.44088681]
  [0.15020234 0.21792886 0.47433312 0.47636886]
  [0.25523235 0.29756527 0.27906712 0.26057921]
  [0.48276159 0.21197904 0.4956306  0.24626133]]

 [[0.83848265 0.18013059 0.86215629 0.17829944]
  [0.7505

##**Ordenação e ADD elementos**

In [55]:
rng = np.random.default_rng()
array_1 = rng.random([2,5])
print(f'Array 1 SEM ORDENAÇÃO:\n{array_1}\n')
print(f'Array 1 COM ORDENAÇÃO:\n{np.sort(array_1)}\n')
print(f'Array 1 COM ORDENAÇÃO:\n{np.sort(array_1,  axis = 0)}\n')
print(f'Array 1 COM ORDENAÇÃO:\n{np.sort(array_1, axis = 1)}\n')

# CONCATENAÇÃO

array_2 = rng.random([2,1])
print(f'ARRAY 2:\n{array_2}\n')

array_concatenado = np.concatenate([array_1,array_2], axis = 1)
print(f'Array Concatenado:\n{array_concatenado}\n')

array_concatenado_2 = np.hstack([array_1,array_2])
print(f'Array Concatenado:\n{array_concatenado_2}\n')


Array 1 SEM ORDENAÇÃO:
[[0.07415085 0.74236675 0.88313351 0.56134348 0.63675779]
 [0.19569401 0.01846536 0.87578982 0.22036217 0.70544661]]

Array 1 COM ORDENAÇÃO:
[[0.07415085 0.56134348 0.63675779 0.74236675 0.88313351]
 [0.01846536 0.19569401 0.22036217 0.70544661 0.87578982]]

Array 1 COM ORDENAÇÃO:
[[0.07415085 0.01846536 0.87578982 0.22036217 0.63675779]
 [0.19569401 0.74236675 0.88313351 0.56134348 0.70544661]]

Array 1 COM ORDENAÇÃO:
[[0.07415085 0.56134348 0.63675779 0.74236675 0.88313351]
 [0.01846536 0.19569401 0.22036217 0.70544661 0.87578982]]

ARRAY 2:
[[0.67703836]
 [0.69471196]]

Array Concatenado:
[[0.07415085 0.74236675 0.88313351 0.56134348 0.63675779 0.67703836]
 [0.19569401 0.01846536 0.87578982 0.22036217 0.70544661 0.69471196]]

Array Concatenado:
[[0.07415085 0.74236675 0.88313351 0.56134348 0.63675779 0.67703836]
 [0.19569401 0.01846536 0.87578982 0.22036217 0.70544661 0.69471196]]



##**Conhecendo o seu array**

In [56]:
rng = np.random.default_rng()
array_teste_4=rng.random([23,43,17])
# print(array_teste_4) #tensor gigante, muito dificil de saber dados

# descobrindo dados do array

print(f'Quais são as suas dimensões?\n{array_teste_4.ndim}\n')
print(f'Quais o seu formato?\n{array_teste_4.shape}\n')
print(f'Qauntos elementos possui?\n{array_teste_4.size}\n')

Quais são as suas dimensões?
3

Quais o seu formato?
(23, 43, 17)

Qauntos elementos possui?
16813



##**Como mudar o formato de um array**

In [57]:
x = np.arange(0,20)
print(f'Array x:\n{x}\n')
x = x.reshape(4,5)
print(f'Array x:\n{x}\n')
x = x.flatten()
print(f'Array x:\n{x}\n')
y=x.reshape([4,5])
print(f'Array y:\n{y}\n')
y=np.vsplit(y,4)
print(f'Array y:\n{y}\n')


Array x:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array x:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array x:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array y:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array y:
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]



## PLOTLY

In [66]:
#Criando arrays para montar

a = 3/4
b = 2/4
c = 1/4
vetor_a=np.ones(20)
vetor_b=np.ones(20)
vetor_c=np.ones(20)

for i in range (20):
  vetor_a[i]= vetor_a[i - 1] = a**i
  vetor_b[i]= vetor_b[i - 1] = b**i
  vetor_c[i]= vetor_c[i - 1] = c**i
# print(vetor_a)
# print(vetor_b)
# print(vetor_c)

np.savetxt('vetor_a.txt', vetor_a, fmt ='%f', delimiter=';')
np.savetxt('vetor_b.txt', vetor_b, fmt ='%f', delimiter=';')
np.savetxt('vetor_c.txt', vetor_c, fmt ='%f', delimiter=';')


##Plotly - Criando nosso primeiro grafico

In [69]:
array_a = np.loadtxt('vetor_a.txt', dtype = np.float64, delimiter = ';')
array_b = np.loadtxt('vetor_b.txt', dtype = np.float64, delimiter = ';')
array_c = np.loadtxt('vetor_c.txt', dtype = np.float64, delimiter = ';')

# print(array_a)
# print(array_b)
# print(array_c)

array_abc = np.vstack([array_a, array_b, array_c])
print(array_abc)
array_abc = array_abc.transpose()
fig = px.scatter(array_abc,
                 title = 'Gráfico de dispersão teste')
fig.show()
fig2 = px.line(array_abc,
               title = 'Gráfico de linha teste')
fig2.show()

[[7.50000e-01 5.62500e-01 4.21875e-01 3.16406e-01 2.37305e-01 1.77979e-01
  1.33484e-01 1.00113e-01 7.50850e-02 5.63140e-02 4.22350e-02 3.16760e-02
  2.37570e-02 1.78180e-02 1.33630e-02 1.00230e-02 7.51700e-03 5.63800e-03
  4.22800e-03 4.22800e-03]
 [5.00000e-01 2.50000e-01 1.25000e-01 6.25000e-02 3.12500e-02 1.56250e-02
  7.81200e-03 3.90600e-03 1.95300e-03 9.77000e-04 4.88000e-04 2.44000e-04
  1.22000e-04 6.10000e-05 3.10000e-05 1.50000e-05 8.00000e-06 4.00000e-06
  2.00000e-06 2.00000e-06]
 [2.50000e-01 6.25000e-02 1.56250e-02 3.90600e-03 9.77000e-04 2.44000e-04
  6.10000e-05 1.50000e-05 4.00000e-06 1.00000e-06 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00]]


# AULA 2 - TRABALHANDO COM PANDAS

In [70]:
import pandas as pd