<a href="https://colab.research.google.com/github/pqvinicius/logica-programacao-em-python-uninter/blob/main/_LOGICA_DE_PROGRAMA%C3%87%C3%83O_EM_PYTHON_UNINTER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
# LOGICA DE PROGRAMAÇÃO EM PYTHON
# AULAS DE PYTHON DA UNINTER
# COLOCAREI AS AULAS PRATICAS AQUI


# **AULA 1** - trabalhando com numpy e plotly

In [48]:
#importações de libs
import numpy as np
import plotly

In [49]:
#diferença entre array numpy para list in python

#lista normal
num_elementos = 10000000
lista_elementos =[]
for x in range(num_elementos):
  lista_elementos.append(x)
print(lista_elementos[-1])

9999999


In [50]:
# lista numpy
array_elementos = np.arange(num_elementos)
print(array_elementos[-1])

9999999


## **Criação de Arrays em Numpy**

In [58]:

array_teste = np.array([1,2,3,4,5,7,8,9,10])
print(f'COM VARIAVEL: Criação de array numpy utilizando o método .array:\n{array_teste}\n')
print(f'DIRETO NO PRINT: Criação de array numpy utilizando o método .array:\n{np.array([1,2,3,4,5,7,8,9,10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de zeros utilizando o método .zeros:\n{np.zeros([10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .ones:\n{np.ones([10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .empy:\n{np.empty([10])}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .arange:\n{np.arange(10)}\n')
print(f'DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .linspace:\n{np.linspace(0,100,num=101)}\n')



COM VARIAVEL: Criação de array numpy utilizando o método .array:
[ 1  2  3  4  5  7  8  9 10]

DIRETO NO PRINT: Criação de array numpy utilizando o método .array:
[ 1  2  3  4  5  7  8  9 10]

DIRETO NO PRINT: Criação de array numpy de zeros utilizando o método .zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .empy:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .arange:
[0 1 2 3 4 5 6 7 8 9]

DIRETO NO PRINT: Criação de array numpy de uns utilizando o método .linspace:
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  

## **TIPOS DE DADOS**

In [77]:
array_perfomance = np.zeros(num_elementos)
print(array_perfomance.dtype) #verificando tipo de dado do aray
print(array_perfomance)
array_perfomance = np.zeros(num_elementos, dtype=np.int8)
print(array_perfomance.dtype)
print(array_perfomance)

float64
[0. 0. 0. ... 0. 0. 0.]
int8
[0 0 0 ... 0 0 0]
